# kubectl create configmap zabbix-hpa-custom-config --from-file=hpa_conf/ -n zbx

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  my-script.sh: |
    #!/bin/bash
    echo "Hello from my script!"